# Generated by Django 4.0.3 on 2022-04-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginFaceDetection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
