# Generated by Django 4.0.3 on 2022-04-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginFaceDetection', '0002_remove_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
