# Generated by Django 4.0.3 on 2022-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginFaceDetection', '0004_alter_users_options_rename_photo_users_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Contrasena'),
        ),
        migrations.AlterField(
            model_name='users',
            name='usuario',
            field=models.CharField(max_length=30, verbose_name='Usuario'),
        ),
    ]
