# Generated by Django 4.0.3 on 2022-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginFaceDetection', '0006_alter_users_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='foto',
            field=models.CharField(blank=True, max_length=10, verbose_name='Foto'),
        ),
    ]
