# Generated by Django 4.0.3 on 2022-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginFaceDetection', '0008_remove_users_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='foto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto'),
        ),
    ]
